"""adding antipode coefficient calculation table

Revision ID: 16d50a2c874c
Revises: c46f32e8ad42
Create Date: 2020-03-09 01:16:45.307449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d50a2c874c'
down_revision = 'c46f32e8ad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antipode_coefficient_calculation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('name_a', sa.String(), nullable=False),
    sa.Column('latitude_a', sa.Float(), nullable=False),
    sa.Column('longitude_a', sa.Float(), nullable=False),
    sa.Column('name_b', sa.String(), nullable=False),
    sa.Column('latitude_b', sa.Float(), nullable=False),
    sa.Column('longitude_b', sa.Float(), nullable=False),
    sa.Column('is_namesake', sa.Boolean(), nullable=False),
    sa.Column('antipode_coefficient', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antipode_coefficient_calculation_antipode_coefficient'), 'antipode_coefficient_calculation', ['antipode_coefficient'], unique=False)
    op.create_index(op.f('ix_antipode_coefficient_calculation_id'), 'antipode_coefficient_calculation', ['id'], unique=False)
    op.create_index(op.f('ix_antipode_coefficient_calculation_is_namesake'), 'antipode_coefficient_calculation', ['is_namesake'], unique=False)
    op.create_index(op.f('ix_antipode_coefficient_calculation_name_a'), 'antipode_coefficient_calculation', ['name_a'], unique=False)
    op.create_index(op.f('ix_antipode_coefficient_calculation_name_b'), 'antipode_coefficient_calculation', ['name_b'], unique=False)
    op.create_index(op.f('ix_antipode_coefficient_calculation_timestamp'), 'antipode_coefficient_calculation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antipode_coefficient_calculation_timestamp'), table_name='antipode_coefficient_calculation')
    op.drop_index(op.f('ix_antipode_coefficient_calculation_name_b'), table_name='antipode_coefficient_calculation')
    op.drop_index(op.f('ix_antipode_coefficient_calculation_name_a'), table_name='antipode_coefficient_calculation')
    op.drop_index(op.f('ix_antipode_coefficient_calculation_is_namesake'), table_name='antipode_coefficient_calculation')
    op.drop_index(op.f('ix_antipode_coefficient_calculation_id'), table_name='antipode_coefficient_calculation')
    op.drop_index(op.f('ix_antipode_coefficient_calculation_antipode_coefficient'), table_name='antipode_coefficient_calculation')
    op.drop_table('antipode_coefficient_calculation')
    # ### end Alembic commands ###
