"""adding feedback table

Revision ID: bc8e2176b9b4
Revises: 16d50a2c874c
Create Date: 2020-03-10 06:01:36.472329

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bc8e2176b9b4"
down_revision = "16d50a2c874c"
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    # data_upgrades()


def downgrade():
    # data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("instagram_handle", sa.String(), nullable=True),
        sa.Column("twitter_handle", sa.String(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
    op.create_index(op.f("ix_feedback_name"), "feedback", ["name"], unique=False)
    op.create_index(
        op.f("ix_feedback_timestamp"), "feedback", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_timestamp"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_name"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
