"""creating a page hit table

Revision ID: c46f32e8ad42
Revises: 
Create Date: 2020-03-08 12:51:56.297752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46f32e8ad42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_hit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_hit_id'), 'page_hit', ['id'], unique=False)
    op.create_index(op.f('ix_page_hit_timestamp'), 'page_hit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_hit_timestamp'), table_name='page_hit')
    op.drop_index(op.f('ix_page_hit_id'), table_name='page_hit')
    op.drop_table('page_hit')
    # ### end Alembic commands ###
